image: python:3.9

stages:
  - test
  - build
  - release

variables:
  VIRTUAL_ENV: .venv
  PATH: "$VIRTUAL_ENV/bin:$PATH"

before_script:
  - python -m venv $VIRTUAL_ENV
  - pip install --upgrade pip
  # Если requirements.txt не используется, зависимости можно установить из pyproject.toml
  - pip install -r requirements.txt || true
  - pip install uv pytest python-semantic-release hvac pydantic

test:
  stage: test
  script:
    - pytest

build:
  stage: build
  script:
    - uv build
  artifacts:
    paths:
      - dist/

release:
  stage: release
  script:
    - semantic-release publish
  only:
    - master
